language: python

python:
  - 3.7

before_install:
  - env
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pytest --cov=pyrsyslogredis tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
